pipeline:
  secrets:
    image: php:7.2-cli-alpine
    commands:
      - env
      - echo $SLACK
      - echo ${SLACK}
      - echo $${SLACK}
    secrets: [ slack ]


  backend:
    image: php:7.2-cli-alpine
    commands:
      - curl https://getcomposer.org/installer > composer-install.php
      - php composer-install.php
      - php composer.phar install
      - php bin/phpspec run

  notify:
    image: plugins/slack
    webhook: $SLACK
    channel: ops
    username: drone
    secrets: [ slack ]
