pipeline:
  backend:
    image: php:7.2-cli-alpine
    commands:
      - ls -al .
      - curl https://getcomposer.org/installer > composer-install.php
      - php composer-install.php
      - ls -al .
      - composer install
      - php bin/phpspec run

  notify:
    image: plugins/slack
    channel: developers
    username: drone
